// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/api/proto/vote.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PollID        string                 `protobuf:"bytes,2,opt,name=PollID,proto3" json:"PollID,omitempty"`
	FieldID       uint64                 `protobuf:"varint,3,opt,name=FieldID,proto3" json:"FieldID,omitempty"`
	Anonim        bool                   `protobuf:"varint,4,opt,name=Anonim,proto3" json:"Anonim,omitempty"`
	UserID        string                 `protobuf:"bytes,5,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_pkg_api_proto_vote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_vote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_vote_proto_rawDescGZIP(), []int{0}
}

func (x *Vote) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Vote) GetPollID() string {
	if x != nil {
		return x.PollID
	}
	return ""
}

func (x *Vote) GetFieldID() uint64 {
	if x != nil {
		return x.FieldID
	}
	return 0
}

func (x *Vote) GetAnonim() bool {
	if x != nil {
		return x.Anonim
	}
	return false
}

func (x *Vote) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type RequestGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGet) Reset() {
	*x = RequestGet{}
	mi := &file_pkg_api_proto_vote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGet) ProtoMessage() {}

func (x *RequestGet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_vote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGet.ProtoReflect.Descriptor instead.
func (*RequestGet) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_vote_proto_rawDescGZIP(), []int{1}
}

func (x *RequestGet) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type RequestUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUpdate) Reset() {
	*x = RequestUpdate{}
	mi := &file_pkg_api_proto_vote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpdate) ProtoMessage() {}

func (x *RequestUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_vote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpdate.ProtoReflect.Descriptor instead.
func (*RequestUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_vote_proto_rawDescGZIP(), []int{2}
}

func (x *RequestUpdate) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RequestUpdate) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RequestUpdate) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_api_proto_vote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_vote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_vote_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RequestDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDelete) Reset() {
	*x = RequestDelete{}
	mi := &file_pkg_api_proto_vote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDelete) ProtoMessage() {}

func (x *RequestDelete) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_vote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDelete.ProtoReflect.Descriptor instead.
func (*RequestDelete) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_vote_proto_rawDescGZIP(), []int{4}
}

func (x *RequestDelete) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type RequestCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          *Vote                  `protobuf:"bytes,1,opt,name=Vote,proto3" json:"Vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCreate) Reset() {
	*x = RequestCreate{}
	mi := &file_pkg_api_proto_vote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreate) ProtoMessage() {}

func (x *RequestCreate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_vote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreate.ProtoReflect.Descriptor instead.
func (*RequestCreate) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_vote_proto_rawDescGZIP(), []int{5}
}

func (x *RequestCreate) GetVote() *Vote {
	if x != nil {
		return x.Vote
	}
	return nil
}

var File_pkg_api_proto_vote_proto protoreflect.FileDescriptor

const file_pkg_api_proto_vote_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/api/proto/vote.proto\"x\n" +
	"\x04Vote\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06PollID\x18\x02 \x01(\tR\x06PollID\x12\x18\n" +
	"\aFieldID\x18\x03 \x01(\x04R\aFieldID\x12\x16\n" +
	"\x06Anonim\x18\x04 \x01(\bR\x06Anonim\x12\x16\n" +
	"\x06UserID\x18\x05 \x01(\tR\x06UserID\"\x1c\n" +
	"\n" +
	"RequestGet\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"G\n" +
	"\rRequestUpdate\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x03 \x01(\tR\x05Value\"0\n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"\x1f\n" +
	"\rRequestDelete\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"*\n" +
	"\rRequestCreate\x12\x19\n" +
	"\x04Vote\x18\x01 \x01(\v2\x05.VoteR\x04Vote2\xa1\x01\n" +
	"\vVoteService\x12#\n" +
	"\vGetByPollID\x12\v.RequestGet\x1a\x05.Vote0\x01\x12#\n" +
	"\x06Update\x12\x0e.RequestUpdate\x1a\t.Response\x12#\n" +
	"\x06Delete\x12\x0e.RequestDelete\x1a\t.Response\x12#\n" +
	"\x06Create\x12\x0e.RequestCreate\x1a\t.ResponseB\x14Z\x12./pkg/api/protobufb\x06proto3"

var (
	file_pkg_api_proto_vote_proto_rawDescOnce sync.Once
	file_pkg_api_proto_vote_proto_rawDescData []byte
)

func file_pkg_api_proto_vote_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_vote_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_vote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_vote_proto_rawDesc), len(file_pkg_api_proto_vote_proto_rawDesc)))
	})
	return file_pkg_api_proto_vote_proto_rawDescData
}

var file_pkg_api_proto_vote_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_api_proto_vote_proto_goTypes = []any{
	(*Vote)(nil),          // 0: Vote
	(*RequestGet)(nil),    // 1: RequestGet
	(*RequestUpdate)(nil), // 2: RequestUpdate
	(*Response)(nil),      // 3: Response
	(*RequestDelete)(nil), // 4: RequestDelete
	(*RequestCreate)(nil), // 5: RequestCreate
}
var file_pkg_api_proto_vote_proto_depIdxs = []int32{
	0, // 0: RequestCreate.Vote:type_name -> Vote
	1, // 1: VoteService.GetByPollID:input_type -> RequestGet
	2, // 2: VoteService.Update:input_type -> RequestUpdate
	4, // 3: VoteService.Delete:input_type -> RequestDelete
	5, // 4: VoteService.Create:input_type -> RequestCreate
	0, // 5: VoteService.GetByPollID:output_type -> Vote
	3, // 6: VoteService.Update:output_type -> Response
	3, // 7: VoteService.Delete:output_type -> Response
	3, // 8: VoteService.Create:output_type -> Response
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_vote_proto_init() }
func file_pkg_api_proto_vote_proto_init() {
	if File_pkg_api_proto_vote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_vote_proto_rawDesc), len(file_pkg_api_proto_vote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_vote_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_vote_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_vote_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_vote_proto = out.File
	file_pkg_api_proto_vote_proto_goTypes = nil
	file_pkg_api_proto_vote_proto_depIdxs = nil
}
